apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: web
  namespace: demo
  labels:
    release: prom-stack
spec:
  selector:
    matchLabels:
      app: web
  namespaceSelector:
    matchNames: ["demo"]
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
